### ISSUE TITLE
JS files load order

### ISSUE THREAD

**Issue by Nyconing** [JocysCom/JsClasses#6]
As I can see, loading JS file with incorrect order will get crash by a big dinosaur.
For example, `system.debug.js` shall load first.
I have review all your codes and documentation, and your deleted file **JocysComJavaScriptClasses.zip**(I dont know why you deleted, you may update the link on documentation website) 
Still not found some clue.

**Comment by Nyconing** [comment]
I have removing `debug` suffix naming in JS files which can cause wrong ordering, and sort it with **A-Z** ordering. It is load fine now. You may review and adding it to your documentation.

```
system.debug.js
systembigint.debug.js
systembitconverter.debug.js
systemcollections.debug.js
systemconfiguration.debug.js
systemconvert.debug.js
systemdata.debug.js
systemdrawing.debug.js
systemextensionsarray.debug.js
systemglobalizationkeyboardlayouts.debug.js
systemgps.debug.js
systemio.debug.js
systemiocompression.debug.js
systemlinq.debug.js
systemsecurity.debug.js
systemsecuritycryptography.debug.js
systemsecuritycryptographyaes.debug.js
systemsecuritycryptographyhmacmd5.debug.js
systemsecuritycryptographyhmacsha1.debug.js
systemsecuritycryptographyhmacsha256.debug.js
systemsecuritycryptographymd5.debug.js
systemsecuritycryptographyrc2.debug.js
systemsecuritycryptographyrc4.debug.js
systemsecuritycryptographyrsa.debug.js
systemsecuritycryptographysha1.debug.js
systemsecuritycryptographysha256.debug.js
systemsecuritypassword.debug.js
systemtesttoolsunittesting.debug.js
systemtext.debug.js
systemtextcodecolorizer.debug.js
systemtimezoneinfo
systemweb.debug.js
systemwebmobile.debug.js
systemwebui.debug.js
systemwebuihtmlcontrols.debug.js
systemwebuihtmlcontrolstextbox.debug.js
systemwebuiinterface.debug.js
systemwebuishortkeys.debug.js
systemwebuitreeview.debug.js
systemwebuiwebcontrols.debug.js
systemwebuiwebcontrolsdialogbox.debug.js
systemwebuiwebcontrolslistview.debug.js
systemwindowsformskeys.debug.js
systemxml.debug.js
```

**Comment by EJocys** [comment]
Thank you, I will add this to documentation. Probably during this weekend.

I removed JocysComJavaScriptClasses.zip, because GitHub admins are not happy when I include large binary files into their source control database. Binary files increase their database by a lot, even when binary change is very small. I had to use "Release" feature" https://github.com/JocysCom/JsClasses/releases and must point all download links to it.

Release page contains link to full zip archive:
ZIP: https://github.com/JocysCom/JsClasses/archive/2018.9.6.0.zip

There is nothing to compile so I could use this default GitHub URL for downloads:
https://github.com/JocysCom/JsClasses/archive/master.zip
